apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-demo
  template:
    metadata:
      labels:
        app: ml-demo
    spec:
      containers:
      - name: ml
        image: docker.io/lcombarroiron/k8s-ml:v0
        ports:
        - containerPort: 8000
